### PR TITLE
feat: Create a Login UI for the website

### LINKED ISSUE #50: Design a Sign-In and Registration UI
We need a well-designed user interface (UI) for our sign-in and registration process. We want to enhance the user experience and create a seamless journey for new and returning users.

**Desired Features:**
1. Clear and prominent sign-in and registration options.
2. Intuitive form fields with appropriate labels for username, password, email, and any additional required information.
3. Error handling and validation for invalid or missing inputs.
4. Password strength meter to guide users in creating secure passwords.
5. Optional "Remember Me" checkbox for returning users.
6. Clear and easy-to-understand error messages for authentication failures.
7. Social media integration for sign-in and registration (if applicable).
8. Responsive design that adapts to different screen sizes (mobile, tablet, desktop).

**Design Considerations:**
1. Use a modern and visually appealing design that aligns with our brand identity.
2. Consider accessibility guidelines and ensure the UI is usable for people with disabilities.
3. Ensure consistency in design elements throughout the sign-in and registration process.
4. Use appropriate typography, colors, and spacing to enhance readability and aesthetics.
5. Incorporate feedback from user testing and iterate on the design to improve usability.

_Note:_ Once the design is ready, we will work with our development team to integrate it into our existing sign-in and registration flow. If you have any questions or need further clarification, please don't hesitate to ask. Thank you for your assistance!

### LINKED ISSUE #159: Login/SignUp Page
currently there is no login and signup page.
I am thinking of making one, can you assign this to me?

### PR DESCRIPTION
**Pull request by MahendraDani**
## Outcomes
- Fixes #159 and #198
- Partially fixes #50 by implementing the `Login ModalUI` in this PR.

## Features Added
1. Created a fully responsive `Login Page UI` for the website.
2. User can login to the website using `email` and `password`.
3. The `Login modal` can be close by clicking on the `close-icon` or clicking anywhere outside the modal on the screen.

### Minor changes
1. Improved the spacing of `navbar-links`.
2. Added hover effect for the `Login` button.

This design is made with guidance of @royalpinto007 .  

## Video/Screenshots

https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/32b97e4e-4d98-4d80-ba90-70617e8f0ba4

### CODE REVIEW

**Comment by MahendraDani** [comment]
@royalpinto007 If there are any changes please let me know.
Thanks!

**Comment by MahendraDani** [comment]
@royalpinto007 If this PR is good, I can also implement the `Sign up` page for the website.
Please provide the guidelines accordingly.
Thanks!

**Comment by royalpinto007** [comment]
LGTM, go ahead with the "Sign up" page!

**Comment by MahendraDani** [comment]
@royalpinto007 For sign-up should I make a new page linked from `create account` link of `Login Modal` ?

Are you going to merge both Login and sign-up page together or should I wait until you close this PR first?

Thanks!

**Comment by royalpinto007** [comment]
Add it to the same PR, I don't think a fresh PR is necessary for this, and yeah you can make a modal similar to login linking it through "create account"!

**Comment by MahendraDani** [comment]
Alright ! Will add the commits to the same PR and get back to you.
Thanks!

**Comment by MahendraDani** [comment]
- Completely fixes #50  
@royalpinto007 I have created both the `Signup` and `Login` modals for our website.

## Features added in signup Modal
1. The outline of the `Confirm Password` field turns **green** when the its value matches with that of `Create Password` else remains **red** which provides next level user experience.

## Videos/Screenshots
- On desktop View

https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/63b89c42-464c-409f-897b-b74328eb4066

- On mobile view

[fix_stoccion_signup_2.webm](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/361be3e6-2eb5-4be3-98ea-633cc1d1f2eb)

**Comment by MahendraDani** [comment]
@royalpinto007 If there are any changes please let me know.
Please merge this PR I have really worked hard to make the login/signup process seamless from user's point of view.

Thanks!

**Comment by MahendraDani** [comment]
@royalpinto007 This branch is showing conflicts but we will change to change the 89th line in `client/src/components/Navbar.jsx` to `<div className="fixed inset-0 z-10" />` because the `Signup` and `Login` modals should be above any other elements of the website.

Please look into this.
Thanks!

**Comment by MahendraDani** [comment]
@royalpinto007 
Would you please review this PR.
I have created the `sign-up` and `login` modals as suggested by you.
Thanks

**Comment by royalpinto007** [comment]
Perfect, thank you so much @MahendraDani :)

**Review by royalpinto007 — APPROVED** [review]

**Pull request merged**
