### PR TITLE
feat: Add pages for navlinks

### LINKED ISSUE #181: feat : Add pages for the navlinks
## Description 
The links in navigation are not functional. Each navigation link such as `Dashboard`, `Stocks`, etc should redirect to their respective pages.

I would like to work on this issue!

### PR DESCRIPTION
**Pull request by MahendraDani**
Fixes #181 

## Description
The navlinks route to their respective pages.
> Note: There is no appropriate content an these pages yet. They are just initialized and the content will be added soon.

## Changes
I have updated the file structure for `/client/src` directory as follows:
```yaml
client/src:
- assets/
- components/
- pages:
   - Cryptocurrencies.jsx
   - Dashboard.jsx
   - Derivates.jsx
   - Homepage.jsx
   - Institutional.jsx
   - News.jsx
   - NFT.jsx
   - Stocks.jsx
   - Support.jsx
   - Trade.jsx
```

## Results

https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/77bb22cb-2c9a-44dd-9d20-75a4a5b8a710

### CODE REVIEW

**Comment by royalpinto007** [comment]
Hi @MahendraDani, 
The changes look great, but please make sure that the navigation bar does not disappear when we navigate to a separate page.
Thanks!

**Comment by MahendraDani** [comment]
@royalpinto007 I have added Navbar to each pages. Please let me know if there are any changes!
Thanks!

**Comment by royalpinto007** [comment]
Great, please update the video too :)

**Comment by MahendraDani** [comment]
Yeah! Sure

**Comment by royalpinto007** [comment]
Cool, thank you so much :)

**Review by royalpinto007 — APPROVED** [review]

**Pull request merged**
