### PR TITLE
style: improve sign up form and add functionalities

### LINKED ISSUE #345: [Style]: Improve Sign Up UI
We might need to revamp the sign up form for better user experience.
Currently, it looks ordinary.

image

We can use tailwind css to its fullest potential to revamp the sign up form by 
- adding icons appropriate for fields
- adding images to make it interactive
- adding show/hide password functionality etc...

P.S.: Please assign this issue to me under GSSoC '23. Thank You!

### PR DESCRIPTION
**Pull request by rishuraj1**
## Closes #345 

Improved Sign Up form

- add: show/hide password functionality for better user exp.
- add: icons appropriate for input fields (email, password) for better UI exp.
- add: social media icons for future OAuth implementation.
- changes: overall styles and bg color according to the theme of the website.

## Screenshots :

before changes : 

image

After changes :

image

### CODE REVIEW

**Comment by rishuraj1** [comment]
image


@royalpinto007

**Comment by rishuraj1** [comment]
image


@royalpinto007

**Comment by royalpinto007** [comment]
Can you please resolve the conflicts?
We still need to work a lot on the styling part and also on the image. But let's address those in a separate issue.

**Comment by rishuraj1** [comment]
@royalpinto007  please check now

**Comment by royalpinto007** [comment]
Cool, thanks!

**Review by royalpinto007 — APPROVED** [review]

**Pull request merged**
