### PR TITLE
Handled the contact us messages

### PR DESCRIPTION
**Pull request by Deepanshu0703**
Created the model for contact us messages and created routes for get post and one and all message deletion route and adde to main App.js

### CODE REVIEW

**Comment by royalpinto007** [comment]
Not quite sure, what do you mean by that, please be clear, thanks!

**Comment by Deepanshu0703** [comment]
I have created model for message getting from contact us page and routes to store them

**Review by royalpinto007 — APPROVED** [review]

**Comment by Deepanshu0703** [comment]
Plz assign it a level ,GSSoC . Thanks

**Comment by Deepanshu0703** [comment]
> Plz assign it a level ,GSSoC . Thanks

Hey  @royalpinto007  plz assign a level and gssoc labels

**Comment by royalpinto007** [comment]
Sure, no worries!

**Pull request merged**
