### PR TITLE
Feature/transparent logo

### PR DESCRIPTION
**Pull request by Shoetan**
Close: Stoccoin Logo Has White Background Causing Issues with Dark Mode #31

Edited the stoccoin logo to have a transparent background. The white background was causing the toggling to dark mode affecting the overall user experience.
logo code

### CODE REVIEW

**Comment by royalpinto007** [comment]
@Shoetan 
I noticed that in addition to the logo file, you've made changes to other files as well. Can you please clarify if these changes were required to make the logo change or if they are from previous commits you made? It would be helpful to have a clear understanding of the changes made.

**Comment by royalpinto007** [comment]
@Shoetan 
I noticed that you deleted the package-lock.json file and replaced it with a yarn.lock file in our project. While both files serve similar purposes, they are used by different package managers (npm and Yarn). As a result, replacing the package-lock.json file with a yarn.lock file could cause issues to the project as it is being managed using npm instead of Yarn.

In addition, the yarn.lock file may not contain all the same information as the package-lock.json file, which could lead to potential issues or lost information.

Therefore, I recommend that we stick to using the package-lock.json file for managing our project's dependencies, unless we have a specific reason to switch to Yarn. This will help ensure that our project's dependencies are installed in a consistent manner across different environments, and avoid any potential issues or conflicts.

Thank you for your understanding and cooperation.

**Comment by Shoetan** [comment]
@royalpinto007 Thank you for the feedback I will stick to using NPM for this project. I use yarn by default.  I will suggest all previous PRs be closed while I revert to NPM and create a new PR to close the transparent logo and dark mode issue.

**Comment by royalpinto007** [comment]
You're welcome! It sounds like a good plan to stick with NPM for this project, and I'm glad that my feedback was helpful in making that decision. As for the previous PRs, it's up to you whether you want to close them or keep them open. However, if you think it's best to start fresh with a new PR to address the transparent logo and dark mode issue, that sounds like a good approach.

**Comment by Shoetan** [comment]
Thank you for understanding. So they are no conflicts in the future I would prefer the new PR route to have everything clean and fresh. Just In case someone else comes across this project in the future.  I am reverting to NPM  from Yarn this PR is a closed comment.

**Pull request closed without merging**
