### PR TITLE
Update README.md

### LINKED ISSUE #71: add badges in readme
I want to add various badges in readme
badges

### PR DESCRIPTION
**Pull request by S-ishita**
Closes #71 
Screenshot from 2023-05-20 12-04-26

### CODE REVIEW

**Comment by royalpinto007** [comment]
Hi @S-ishita, 
You can eliminate the first row as it is not needed, and please note that you are not following our contribution guidelines. I kindly request you to take a look at them. 
Thank you!

**Comment by S-ishita** [comment]
hey  @royalpinto007 .. i removed the first row. And me will keep in mind the guidelines from next time.

**Comment by S-ishita** [comment]
@royalpinto007 do you want me to raise new pr or will this work for this time?

**Comment by royalpinto007** [comment]
Hey @S-ishita, 
Please raise a new PR or just revert and commit again by following the contribution guidelines, since we don't accept the PR's which don't follow our contribution guidelines :)
Thanks for understanding!

**Pull request merged**
