### PR TITLE
[feat] add language translate feature #66

### PR DESCRIPTION
**Pull request by vaibhav-xt**
I am GSSOC 2023 contributor and added the language translation feature using the i18next library. 

### Video:-

https://github.com/Stoccoin-Official/Stoccoin-Website/assets/90946899/82081e43-b441-47b5-9080-6bb2572739d0

### CODE REVIEW

**Comment by royalpinto007** [comment]
Hi @vaibhav-xt,
The implementation of the feature looks good to me, but the names of the languages don't seem to be relevant. Please look into this and see if something can be done.
Thanks!

**Comment by vaibhav-xt** [comment]
@royalpinto007 should I change languages nam "en" to English like that

**Comment by royalpinto007** [comment]
Exactly, you got it right!

**Comment by vaibhav-xt** [comment]
> Exactly, you got it right!

Ok

**Comment by vaibhav-xt** [comment]
Hey, I made the changes. 

https://github.com/Stoccoin-Official/Stoccoin-Website/assets/90946899/8406aac9-22e5-4085-a0b5-fbfb5beab864

**Comment by royalpinto007** [comment]
LGTM, please resolve conflicts, thanks!

**Comment by vaibhav-xt** [comment]
> LGTM, please resolve conflicts, thanks!


@royalpinto007 done 👍

**Comment by royalpinto007** [comment]
Hey @vaibhav-xt!
We analyzed the changes and found that this would require a lot of data for every language that we need to implement. Can you find some other way, such as fetching APIs or using alternative methods, to achieve the same goal instead of storing data like this? We aim to have an optimized website in the end, don't we?
Please look into this, thanks!

**Pull request closed without merging**
