### PR TITLE
Added Show forgot Password Page

### PR DESCRIPTION
**Pull request by AtharvaRaut2002**
I have added Forgot Password Page which is matching with the theme. 
Screenshot 2023-06-15 102546

Kindly check this PR and let me know the changes if any

### CODE REVIEW

**Comment by royalpinto007** [comment]
Cool, thank you so much @AtharvaRaut2002!

**Review by royalpinto007 — APPROVED** [review]

**Comment by AtharvaRaut2002** [comment]
Thank you so much @royalpinto007 for merging the pull request.

**Comment by AtharvaRaut2002** [comment]
@royalpinto007 Add this pr under Gssoc'2023.

**Comment by royalpinto007** [comment]
Alright!

**Pull request merged**
