### PR TITLE
Footer Links When hovered get's underlined to focus on Link

### PR DESCRIPTION
**Pull request by Gurmeet-Singh657**
Issue Number 186 resolved wherein now on hovering underlining animation on footer is shown !!
Thanks for assigning me this issue.
Please merge my pull request.
Thank You @royalpinto007 
image

### CODE REVIEW

**Comment by royalpinto007** [comment]
Please resolve conflicts, thanks!

**Comment by Gurmeet-Singh657** [comment]
@royalpinto007 Resolved the Conflicts ✅

**Comment by Gurmeet-Singh657** [comment]
@royalpinto007 I think u forgot to merge my Pull request

**Comment by royalpinto007** [comment]
Can you please resolve the conflicts again?
Missed this one, thanks for understanding :)

**Comment by royalpinto007** [comment]
Any update? @Gurmeet-Singh657

**Pull request closed without merging**
