### PR TITLE
refactor: made accordion interactive

### PR DESCRIPTION
**Pull request by UthpalSuvarna**
- Added QnA component to display frequently asked questions.
- Added interactivity to expand and collapse question answers.
Screenshot from 2023-07-06 08-17-10
Screenshot from 2023-07-06 08-22-06

### CODE REVIEW

**Comment by UthpalSuvarna** [comment]
Sure

**Comment by royalpinto007** [comment]
Looks like your PR got conflicts, can you please try to resolve them?

**Comment by UthpalSuvarna** [comment]
Resolved conflicts

**Comment by royalpinto007** [comment]
Great!

**Review by royalpinto007 — APPROVED** [review]

**Comment by royalpinto007** [comment]
Thanks @UthpalSuvarna :)

**Pull request merged**
