### PR TITLE
style: Improve Sign In form with added functionalities

### LINKED ISSUE #344: [Style]: Improve Sign In UI
We might need to revamp the log in form for better user experience.
Currently, it looks ordinary.

image

We can use tailwind css to its fullest potential to revamp the login form by 
- adding icons appropriate for fields
- adding images to make it interactive
- adding show/hide password functionality etc...

P.S.: Please assign this issue to me under GSSoC '23. Thank You!

### PR DESCRIPTION
**Pull request by rishuraj1**
## Closes #344 

Improved Sign In form

- add: show/hide password functionality for better user exp.
- add: icons appropriate for input fields (email, password) for better UI exp.
- add: social media icons for future OAuth implementation.
- changes: overall styles and bg color according to the theme of the website.

## Screenshots :

before changes : 

image

After changes :

image

image

### CODE REVIEW

**Comment by royalpinto007** [comment]
Instead of "Stoccoin, Welcome back," let's try attaching some images related to the website. Additionally, we can keep the background color white. Let's put in more effort to improve it and make it better!
For inspiration, you can have a look at the attached image :)
image

**Comment by rishuraj1** [comment]
alright @royalpinto007  do you want me to create an additional page for signin and signup ? That's actually good for better user experience

**Comment by rishuraj1** [comment]
image
 
@royalpinto007  done.

**Comment by rishuraj1** [comment]
image

@royalpinto007

**Comment by royalpinto007** [comment]
This looks better; however, we still need to work a lot on the styling part and also on the image. But let's address those in a separate issue. 
Thanks for this :)

**Review by royalpinto007 — APPROVED** [review]

**Pull request merged**
