### PR TITLE
[ADDED]: sitemap.xml

### LINKED ISSUE #338: [ADD]: sitemap.xml
### Is your feature request related to a problem? Please describe.

Not Properly optimized for various search engines.

### Describe the solution you'd like

A sitemap is a file that lists all the pages of a website, helping search engines understand its structure and content. It enhances search engine optimization (SEO) efforts by improving website visibility and indexing. I believe adding sitemap would be a perfect addition to this project.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Killer2OP**
# Sitemap Added 
closes #338

### CODE REVIEW

**Comment by Killer2OP** [comment]
@royalpinto007 Can you please review the PR.

**Review by royalpinto007 — APPROVED** [review]

**Comment by royalpinto007** [comment]
Thanks @Killer2OP :)

**Comment by Killer2OP** [comment]
> Thanks @Killer2OP :)

Can you add the appropriate labels of level and GSSoC to the PR.

**Comment by royalpinto007** [comment]
Sure

**Pull request merged**
