### PR TITLE
Added Count up to the stats section

### PR DESCRIPTION
**Pull request by sumitkr2000**
Hey, @royalpinto007 I have added the count-up animation to the stats section. Wn a user scrolls to the stats section the counter automatically increases. Please review my pr and merge it Thnak you!

- Issue no. #250

### CODE REVIEW

**Comment by royalpinto007** [comment]
Since it looks like a UI change, I expect you to add screenshots or videos for better clarification, thanks!

**Comment by sumitkr2000** [comment]
Here is the screen recording:-

[screen-capture (2).webm](https://github.com/Stoccoin-Official/Stoccoin-Website/assets/100675296/fafe1068-1db2-4c37-a742-60a096ec3cf0)

**Review by royalpinto007 — APPROVED** [review]

**Comment by royalpinto007** [comment]
Cool, thanks @sumitkr2000!

**Comment by sumitkr2000** [comment]
@royalpinto007 Please add level tag

**Pull request merged**
