### PR TITLE
style: improve footer

### LINKED ISSUE #346: [Style]: Improve Footer section
image

We can use tailwind css to its fullest potential to revamp the footer section by 
- rearranging icons of social media and paragraphs
- adding styles to icons and links
- additionally adding a link to this repo.

P.S.: Please assign this issue to me under GSSoC '23. Thank You!

### PR DESCRIPTION
**Pull request by rishuraj1**
## Improvements

- add: classic footer style
- add: react icons and corresponding links
- add: styles like hover effects
- rearranged the whole section with matching color theme
- tried to make it responsive
- the stoccoin logo at footer also serves as a link to the homepage.

## Screenshots

before:

image

after changes:

image

image

### CODE REVIEW

**Comment by royalpinto007** [comment]
If I am not wrong, this should be the "before" image 
image

**Comment by royalpinto007** [comment]
It doesn't seem like it's placed well, and there seems to be a lot of gap which I think is unnecessary and looks quite odd. Also, the font size of "Follow us" and "Newsletter" looks smaller than the logo size of social media platforms. Either try to update the logo size back to its previous normal size or adjust the font size accordingly. Thanks for understanding!
image

**Comment by rishuraj1** [comment]
@royalpinto007  can you check now.

**Comment by royalpinto007** [comment]
The changes look good, but I still feel that we could arrange the social media icons into two columns. This adjustment would enhance the UI's appearance. Could you please make that change as well?

**Comment by rishuraj1** [comment]
alright, @royalpinto007 once done, i will update.

**Comment by rishuraj1** [comment]
@royalpinto007  done. additionally, I reduced the gap beneath the footer. plz review

image

**Comment by royalpinto007** [comment]
Please fix Koo icon's size, it looks quite larger than other icons!

**Comment by rishuraj1** [comment]
@royalpinto007  I believe its fine right now.

image

**Comment by royalpinto007** [comment]
Ah, it looks similar only. Anyways, let's focus on it as a separate issue. 
Thanks for this :)

**Review by royalpinto007 — APPROVED** [review]

**Comment by rishuraj1** [comment]
@royalpinto007  I think this has to do with the svgs i used for koo icon as it was not available in the react-icons pack, anyways I will try to fix it and provide an optimal solution later. Thanks for the compliments. Please assign apt labels tho. : )

**Pull request merged**
