### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by munish-on-git**
To start the server we should run node App.js not server.js, updated this in readme.md.

### CODE REVIEW

**Comment by royalpinto007** [comment]
Hi @munish-on-git!
The changes are correct, but you are not following our contribution guidelines for writing a commit message. Please take a look at it. 
|Thanks!

**Comment by munish-on-git** [comment]
Thanks @royalpinto007 for guiding,
I have updated my commit according to contribution guidelines .

**Comment by royalpinto007** [comment]
Your commit has conflicts, please resolve them. 
Thanks!

**Comment by munish-on-git** [comment]
Resolved!

**Review by royalpinto007 — APPROVED** [review]

**Comment by royalpinto007** [comment]
Thanks @munish-on-git :)

**Pull request merged**
