### PR TITLE
Added social media icons

### LINKED ISSUE #42: Adding Icons for Social Media Handles
We can add social media icons along with the links, it will make the website visually appealing.
I'd like to work on this if you approve.
2023-05-18 21_08_13-Stoccoin - Brave

something like this maybe?

### PR DESCRIPTION
**Pull request by mukul314**
fixes #42 

Before:
2023-05-20 18_33_48-Stoccoin - Brave

After:
2023-05-20 18_35_34-Stoccoin - Brave

### CODE REVIEW

**Comment by royalpinto007** [comment]
Hey @mukul314,
Since the commit changes the UI, could you please post before and after screenshots as well?
Thanks!

**Comment by mukul314** [comment]
> Hey @mukul314, Since the commit changes the UI, could you please post before and after screenshots as well? Thanks!

Done @royalpinto007 !

**Comment by royalpinto007** [comment]
You need to resolve the conflicts that are taking place. 
Please look into it, thanks!

**Comment by royalpinto007** [comment]
Please resolve the conflicts :)

**Pull request closed without merging**
