### PR TITLE
Implemented dark mode

### PR DESCRIPTION
**Pull request by Shoetan**
Close: https://github.com/Stoccoin-Official/Stoccoin-Website/issues/7

Implemented dark mode by first adding a toggle switch to control light or dark mode.
Used tailwind dark mode utility class to change the background based on the state of the toggle switch.

Dark gif

### CODE REVIEW

**Comment by royalpinto007** [comment]
@Shoetan 
Thank you for implementing the toggle and dark mode feature. I have reviewed the changes and they look great to me. However, I have noticed that the toggle and the dark mode feature do not align with the nav bar. Can you please make some changes to fix that?

Additionally, I would like to remind you to follow the contribution guidelines of the repository. This will ensure that your changes are properly reviewed and integrated into the codebase. Please make sure that you have followed all the guidelines before submitting your changes.

**Comment by Shoetan** [comment]
@royalpinto007 Thank you so much for your feedback I truly appreciate it. I did not notice the misalignment on the navbar. 

I also noticed the stoccoin logo has a white background that does not seem to go away that is the reason for having those white edges when you switch to dark mode. Would it be possible to get the SVG with a transparent background to fix this issue?

**Comment by royalpinto007** [comment]
Great observation! I appreciate you bringing this up. 
Creating a separate issue to fix the logo with a transparent version is definitely the way to go.

**Comment by Shoetan** [comment]
Created a new branch and followed the contributing guide. Closing this PR not to create any conflict or confusion

**Pull request closed without merging**
