### PR TITLE
feat: created a new crypto page

### PR DESCRIPTION
**Pull request by karthiknadar1204**
https://github.com/Stoccoin-Official/Stoccoin-Website/assets/95973644/d7a174bf-26f9-4edb-add7-a0d487fbd89b

The above is the preview of the page we access on clicking the "cryptocurrencies" link on navbar. This is perfectly responsive.

https://github.com/Stoccoin-Official/Stoccoin-Website/assets/95973644/caa63640-8fd2-4ac9-b7e5-4e72746f31f4

The second preview is of the page I have created for individual coins displaying the graph and other info of individual coins,I haven't made this page responsive , Could you please open a separate issue for someone else to make the second page responsive. Hope that's fine.

In the above issue, I have created a basic skeleton of the cryptocurrencies page using the coingecko API, the page still has a lot of scope for improvement , can be done for sure.

The API call might get hindered sometimes as we are using a free api, just go to COinDetails.jsx, comment out the info coming from API, reload and then uncomment..

Closes issue #305

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
Have resolved a merge conflict

**Comment by royalpinto007** [comment]
Hi @karthiknadar1204,
Maybe we can add all of this information to the 'Learn More' section of the cryptocurrencies page instead of the main cryptocurrencies page. 
The charts don't seem great, so you can exclude them. 
Please update it, thanks!

**Comment by karthiknadar1204** [comment]
Ok so remove the charts and shift the links of cards in preview1.mp4 to learn more, is that right?

**Comment by karthiknadar1204** [comment]
Will do and push changes right away

**Comment by royalpinto007** [comment]
Also make sure, you don't change anything in the cryptocurrencies page.

**Comment by karthiknadar1204** [comment]
Will remove any additional files, I was about to add a loader but then forgot to delete the file.
ANything extra?

**Comment by karthiknadar1204** [comment]
@royalpinto007 WIll push the changes by 4:15 and ping you 
Thank you

**Comment by royalpinto007** [comment]
No issues!

**Comment by karthiknadar1204** [comment]
@royalpinto007 I have removed the graph, as for creating a section in learn more, I was thinking of keeping the links as it is, for learn more we could add something else in the near future, it could include info about what is crypto and stuff, what do you say, now changing the path to learn more will involve plethora of complex changes in the path.

Your opinion?

**Comment by karthiknadar1204** [comment]
Screenshot 2023-06-25 at 5 26 19 PM

I have removed the graph but when pushing the changes, it is showing behind the main branch, tried to pull the changes but still showing error

**Comment by royalpinto007** [comment]
But the thing is, we have more data already present on the page that has been created. We just need to customize and style it properly. You can refer to this page for more insights on how we actually want to implement things for this page: https://coinmarketcap.com/

We can keep your cards in the "Learn More" section, as they don't provide significant information. 
I hope you understand. 
Thanks.

> @royalpinto007 I have removed the graph, as for creating a section in learn more, I was thinking of keeping the links as it is, for learn more we could add something else in the near future, it could include info about what is crypto and stuff, what do you say, now changing the path to learn more will involve plethora of complex changes in the path.
> 
> Your opinion?

**Comment by karthiknadar1204** [comment]
works

**Comment by karthiknadar1204** [comment]
> Screenshot 2023-06-25 at 5 26 19 PM
> I have removed the graph but when pushing the changes, it is showing behind the main branch, tried to pull the changes but still showing error

For this issue, for now merge this pr if possible, in my next or, will remove the graph and add the cards to the learn more link as for the change in links, have to alter the routes in App.jsx and already facing issues with pushing the changes after removing the graph, so at least will pull these changes before pushing more

**Comment by karthiknadar1204** [comment]
Dont want to be riddled with unnecessary branch conflicts, the present changes itself involved writing plethora of code, the second cohort of changes should be done latest by tonight or tomorrow afternoon, is that fine @royalpinto007

**Comment by royalpinto007** [comment]
Let me check this, thanks for updating!

**Comment by royalpinto007** [comment]
Could you please create a video showcasing the changes that you have made and add it to the video description?
Thanks!

**Comment by karthiknadar1204** [comment]
In a min, just got rid of the graph in my change

**Comment by karthiknadar1204** [comment]
Screenshot 2023-06-25 at 5 46 20 PM

**Comment by karthiknadar1204** [comment]
The info could me beautified, but here I was focussed on getting up the main functionality via the api

**Comment by royalpinto007** [comment]
I agree, but don't you think we can obtain the same data in the form of a table through the TradingView API as well? (present)
It's just a matter of styling it a bit.

**Comment by karthiknadar1204** [comment]
Definitely possible, coingecko was easier to integrate and work with with the variety of info it had to offer plus I had experience working with it in earlier projects so thought it was a viable option.

**Comment by karthiknadar1204** [comment]
For a tabular view, we can style the incoming info from the API as well, wouldn't make much difference is what I think.

**Comment by karthiknadar1204** [comment]
@royalpinto007 Good to go?
If yes, will open another issue to remove the graph and change the path for the links, tried pushing it to the same branch but branch conflicts and issues while trying to pull into my cloned repo.
Once this is merged and labelled, will pull these changes and wrap up the pertaining tasks in the second issue, how does that sound?
Also can additionally improve the styling according to your ideas/tastes.
Works?

**Comment by karthiknadar1204** [comment]
@royalpinto007 Any update?
I think i have done pretty good work for the starters, will continue changes , but yes.

**Comment by karthiknadar1204** [comment]
@royalpinto007 Any update?
Please merge this so can move forward with improving the feature

**Pull request closed without merging**
